# Generated by Django 3.2.7 on 2021-10-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=50)),
                ('last_name', models.CharField(default='none', max_length=50)),
                ('email', models.CharField(default='none', max_length=50)),
                ('auth_code', models.CharField(default='none', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buzzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('detail', models.CharField(default='none', max_length=100)),
                ('video', models.FileField(blank=True, default='default_files/default.mp4', upload_to='app_files/videos/')),
                ('category', models.CharField(default='none', max_length=50)),
                ('tag1', models.CharField(default='none', max_length=20)),
                ('tag2', models.CharField(default='none', max_length=20)),
                ('tag3', models.CharField(default='none', max_length=20)),
                ('tag4', models.CharField(default='none', max_length=20)),
                ('tag5', models.CharField(default='none', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('detail', models.CharField(default='none', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('video', models.FileField(blank=True, default='default_files/default.mp4', upload_to='app_files/videos/')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionClapConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clap')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solution')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionBuzzerConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buzzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buzzer')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solution')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='buzzer',
            field=models.ManyToManyField(through='main.SolutionBuzzerConnector', to='main.Buzzer'),
        ),
        migrations.AddField(
            model_name='solution',
            name='claps',
            field=models.ManyToManyField(through='main.SolutionClapConnector', to='main.Clap'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem'),
        ),
        migrations.CreateModel(
            name='ProblemClapConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clap')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemBuzzerConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buzzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buzzer')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='buzzer',
            field=models.ManyToManyField(through='main.ProblemBuzzerConnector', to='main.Buzzer'),
        ),
        migrations.AddField(
            model_name='problem',
            name='claps',
            field=models.ManyToManyField(through='main.ProblemClapConnector', to='main.Clap'),
        ),
    ]
