# Generated by Django 3.1.7 on 2022-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Lapp_files/videos/6app_files/videos/4app_files/videos/Napp_files/videos/7app_files/videos/Iapp_files/videos/0app_files/videos/Rapp_files/videos/Fapp_files/videos/V'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='1app_files/videos/Dapp_files/videos/Capp_files/videos/Yapp_files/videos/Yapp_files/videos/8app_files/videos/Mapp_files/videos/Gapp_files/videos/Capp_files/videos/S'),
        ),
    ]
