# Generated by Django 3.1.7 on 2022-01-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Sapp_files/videos/Bapp_files/videos/7app_files/videos/Papp_files/videos/Eapp_files/videos/Papp_files/videos/Lapp_files/videos/5app_files/videos/Napp_files/videos/W'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Mapp_files/videos/Zapp_files/videos/Bapp_files/videos/Zapp_files/videos/Sapp_files/videos/8app_files/videos/Wapp_files/videos/Napp_files/videos/Xapp_files/videos/2'),
        ),
    ]
