# Generated by Django 3.1.7 on 2022-01-01 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220101_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Napp_files/videos/Lapp_files/videos/9app_files/videos/Rapp_files/videos/Sapp_files/videos/6app_files/videos/Happ_files/videos/Xapp_files/videos/8app_files/videos/S'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='2app_files/videos/Bapp_files/videos/Wapp_files/videos/8app_files/videos/Lapp_files/videos/6app_files/videos/Zapp_files/videos/Capp_files/videos/9app_files/videos/P'),
        ),
    ]
