# Generated by Django 3.1.7 on 2022-01-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220128_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/Qapp_files/videos/5app_files/videos/Dapp_files/videos/Capp_files/videos/Qapp_files/videos/Bapp_files/videos/Rapp_files/videos/Zapp_files/videos/7'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Japp_files/videos/Happ_files/videos/Uapp_files/videos/Vapp_files/videos/Happ_files/videos/Kapp_files/videos/7app_files/videos/9app_files/videos/7app_files/videos/I'),
        ),
    ]
