# Generated by Django 3.1.7 on 2022-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220128_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Uapp_files/videos/Gapp_files/videos/Wapp_files/videos/2app_files/videos/Lapp_files/videos/1app_files/videos/Qapp_files/videos/Kapp_files/videos/0app_files/videos/V'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Uapp_files/videos/Rapp_files/videos/Napp_files/videos/Iapp_files/videos/Happ_files/videos/Uapp_files/videos/Happ_files/videos/3app_files/videos/Sapp_files/videos/Y'),
        ),
    ]
