# Generated by Django 3.1.7 on 2022-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220101_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creator',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Wapp_files/videos/8app_files/videos/Napp_files/videos/Wapp_files/videos/5app_files/videos/6app_files/videos/8app_files/videos/Wapp_files/videos/Wapp_files/videos/K'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Wapp_files/videos/Oapp_files/videos/Gapp_files/videos/Qapp_files/videos/Eapp_files/videos/6app_files/videos/3app_files/videos/Yapp_files/videos/Oapp_files/videos/P'),
        ),
    ]
