# Generated by Django 3.1.7 on 2022-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220102_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/Dapp_files/videos/Bapp_files/videos/3app_files/videos/Kapp_files/videos/Napp_files/videos/5app_files/videos/Zapp_files/videos/Uapp_files/videos/3'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Napp_files/videos/Zapp_files/videos/Lapp_files/videos/Sapp_files/videos/9app_files/videos/Gapp_files/videos/2app_files/videos/Bapp_files/videos/7app_files/videos/H'),
        ),
    ]
