# Generated by Django 3.1.7 on 2022-01-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220129_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, upload_to='account_files/videos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Napp_files/videos/5app_files/videos/Lapp_files/videos/Tapp_files/videos/Japp_files/videos/Papp_files/videos/3app_files/videos/4app_files/videos/Napp_files/videos/0'),
        ),
    ]
