# Generated by Django 3.1.7 on 2022-01-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220102_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Bapp_files/videos/4app_files/videos/Uapp_files/videos/Bapp_files/videos/Lapp_files/videos/Capp_files/videos/Wapp_files/videos/Rapp_files/videos/Dapp_files/videos/6'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Zapp_files/videos/Wapp_files/videos/Sapp_files/videos/Fapp_files/videos/4app_files/videos/6app_files/videos/4app_files/videos/8app_files/videos/Mapp_files/videos/N'),
        ),
    ]
