# Generated by Django 3.1.7 on 2022-01-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220129_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/6app_files/videos/Qapp_files/videos/8app_files/videos/Sapp_files/videos/Qapp_files/videos/4app_files/videos/0app_files/videos/Mapp_files/videos/8'),
        ),
    ]
