# Generated by Django 3.1.7 on 2022-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220129_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/cover_image/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/videos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Uapp_files/videos/Fapp_files/videos/5app_files/videos/Oapp_files/videos/Vapp_files/videos/Zapp_files/videos/Oapp_files/videos/Iapp_files/videos/8app_files/videos/P'),
        ),
    ]
