# Generated by Django 3.1.7 on 2022-01-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220102_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Fapp_files/videos/Mapp_files/videos/4app_files/videos/Qapp_files/videos/5app_files/videos/Vapp_files/videos/Tapp_files/videos/7app_files/videos/Yapp_files/videos/7'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Wapp_files/videos/9app_files/videos/9app_files/videos/Fapp_files/videos/Dapp_files/videos/1app_files/videos/Lapp_files/videos/4app_files/videos/Wapp_files/videos/6'),
        ),
    ]
