# Generated by Django 3.1.7 on 2022-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220102_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Tapp_files/videos/Dapp_files/videos/6app_files/videos/Dapp_files/videos/Capp_files/videos/Rapp_files/videos/Iapp_files/videos/Uapp_files/videos/4app_files/videos/U'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Capp_files/videos/7app_files/videos/7app_files/videos/8app_files/videos/Papp_files/videos/2app_files/videos/3app_files/videos/Eapp_files/videos/Wapp_files/videos/Q'),
        ),
    ]
