# Generated by Django 3.1.7 on 2022-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220129_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/onion_pp.jpg', upload_to='account_files/cover_image/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default_video.mp4', upload_to='account_files/videos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='2app_files/videos/Papp_files/videos/Japp_files/videos/Aapp_files/videos/Papp_files/videos/Zapp_files/videos/Eapp_files/videos/Capp_files/videos/Rapp_files/videos/N'),
        ),
    ]
