# Generated by Django 3.1.7 on 2022-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='5app_files/videos/Tapp_files/videos/9app_files/videos/9app_files/videos/Japp_files/videos/Papp_files/videos/Qapp_files/videos/Tapp_files/videos/Bapp_files/videos/Y'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Lapp_files/videos/Fapp_files/videos/7app_files/videos/Mapp_files/videos/Iapp_files/videos/3app_files/videos/1app_files/videos/Eapp_files/videos/Qapp_files/videos/7'),
        ),
    ]
