# Generated by Django 3.1.7 on 2022-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220129_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/default_cover.jpg', upload_to='account_files/cover_image/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/onion_pp.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/1app_files/videos/Uapp_files/videos/Xapp_files/videos/Xapp_files/videos/Xapp_files/videos/Happ_files/videos/Bapp_files/videos/Vapp_files/videos/Q'),
        ),
    ]
