# Generated by Django 3.1.7 on 2022-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Uapp_files/videos/Rapp_files/videos/Oapp_files/videos/7app_files/videos/5app_files/videos/Dapp_files/videos/Rapp_files/videos/Kapp_files/videos/Japp_files/videos/V'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='5app_files/videos/Capp_files/videos/Oapp_files/videos/Happ_files/videos/Napp_files/videos/Yapp_files/videos/Uapp_files/videos/Japp_files/videos/Kapp_files/videos/W'),
        ),
    ]
