# Generated by Django 3.1.7 on 2022-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Mapp_files/videos/Iapp_files/videos/Eapp_files/videos/Dapp_files/videos/8app_files/videos/5app_files/videos/Qapp_files/videos/4app_files/videos/Sapp_files/videos/N'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Dapp_files/videos/Dapp_files/videos/6app_files/videos/6app_files/videos/Japp_files/videos/Eapp_files/videos/Dapp_files/videos/Xapp_files/videos/Mapp_files/videos/6'),
        ),
    ]
