# Generated by Django 3.1.7 on 2022-01-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220129_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/onion_pp.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='4app_files/videos/0app_files/videos/Kapp_files/videos/Uapp_files/videos/Dapp_files/videos/Bapp_files/videos/8app_files/videos/Qapp_files/videos/6app_files/videos/C'),
        ),
    ]
