# Generated by Django 3.1.7 on 2022-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='1app_files/videos/Yapp_files/videos/Yapp_files/videos/Napp_files/videos/Dapp_files/videos/Happ_files/videos/9app_files/videos/1app_files/videos/2app_files/videos/4'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Tapp_files/videos/Kapp_files/videos/Yapp_files/videos/Capp_files/videos/4app_files/videos/Fapp_files/videos/Japp_files/videos/8app_files/videos/Qapp_files/videos/4'),
        ),
    ]
