# Generated by Django 3.1.7 on 2022-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Yapp_files/videos/Mapp_files/videos/7app_files/videos/2app_files/videos/7app_files/videos/Kapp_files/videos/Vapp_files/videos/Japp_files/videos/3app_files/videos/G'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='4app_files/videos/7app_files/videos/0app_files/videos/Napp_files/videos/Kapp_files/videos/6app_files/videos/Fapp_files/videos/Kapp_files/videos/9app_files/videos/4'),
        ),
    ]
