# Generated by Django 3.1.7 on 2022-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220129_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/default_cover.jpg', upload_to='account_files/profile_photos/'),
        ),
    ]
