# Generated by Django 3.1.7 on 2022-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Vapp_files/videos/Wapp_files/videos/Papp_files/videos/Papp_files/videos/Aapp_files/videos/Tapp_files/videos/Wapp_files/videos/1app_files/videos/1app_files/videos/K'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='6app_files/videos/7app_files/videos/Tapp_files/videos/9app_files/videos/Lapp_files/videos/Vapp_files/videos/Eapp_files/videos/Bapp_files/videos/Japp_files/videos/7'),
        ),
    ]
