# Generated by Django 3.1.7 on 2022-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Vapp_files/videos/Iapp_files/videos/Uapp_files/videos/Gapp_files/videos/Uapp_files/videos/Rapp_files/videos/Wapp_files/videos/8app_files/videos/Eapp_files/videos/I'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/Dapp_files/videos/Qapp_files/videos/5app_files/videos/Napp_files/videos/Papp_files/videos/Iapp_files/videos/Wapp_files/videos/1app_files/videos/W'),
        ),
    ]
