# Generated by Django 3.1.7 on 2022-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/default_image.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='cover_image',
            field=models.FileField(blank=True, default='default_files/cover_imm.png', upload_to='app_files/cover_images/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='app_files/videos/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='app_files/videos/'),
        ),
    ]
