# Generated by Django 3.1.7 on 2022-01-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Fapp_files/videos/Rapp_files/videos/Dapp_files/videos/Zapp_files/videos/2app_files/videos/Lapp_files/videos/Gapp_files/videos/Aapp_files/videos/4app_files/videos/K'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Oapp_files/videos/8app_files/videos/Mapp_files/videos/Eapp_files/videos/Rapp_files/videos/Wapp_files/videos/Fapp_files/videos/Happ_files/videos/Dapp_files/videos/0'),
        ),
    ]
