# Generated by Django 3.1.7 on 2022-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='6app_files/videos/Dapp_files/videos/Eapp_files/videos/Fapp_files/videos/9app_files/videos/Wapp_files/videos/Zapp_files/videos/Oapp_files/videos/Gapp_files/videos/7'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Vapp_files/videos/Eapp_files/videos/Uapp_files/videos/Vapp_files/videos/0app_files/videos/Napp_files/videos/Iapp_files/videos/7app_files/videos/8app_files/videos/N'),
        ),
    ]
