# Generated by Django 3.1.7 on 2022-01-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220126_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Oapp_files/videos/4app_files/videos/7app_files/videos/Lapp_files/videos/Aapp_files/videos/3app_files/videos/Zapp_files/videos/1app_files/videos/Zapp_files/videos/U'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='6app_files/videos/1app_files/videos/Bapp_files/videos/7app_files/videos/5app_files/videos/Yapp_files/videos/Gapp_files/videos/Eapp_files/videos/1app_files/videos/P'),
        ),
    ]
