# Generated by Django 3.1.7 on 2022-01-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220126_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Happ_files/videos/Oapp_files/videos/Dapp_files/videos/Qapp_files/videos/9app_files/videos/Happ_files/videos/0app_files/videos/Fapp_files/videos/Aapp_files/videos/K'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='video',
            field=models.FileField(blank=True, default='default_files/default.mp4', upload_to='Xapp_files/videos/Aapp_files/videos/4app_files/videos/4app_files/videos/6app_files/videos/Gapp_files/videos/2app_files/videos/7app_files/videos/Vapp_files/videos/D'),
        ),
    ]
